# .pre-commit-config.yaml
repos:
  # 1. UV: Ensure uv.lock is up to date
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.5.6  # Use the latest version
    hooks:
      - id: uv-lock

  # 2. Ruff: Lint and Format
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.6  # Use the latest version
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix] # Lint and fix
      - id: ruff-format # Format code
