site_name: ''
repo_url: https://github.com/mskmay66/syndicate
repo_name: mskmay66/syndicate
features:
  - navigation.indexes
nav:
  - Home: index.md
  - The Team: meet_the_team.md
  - Getting Started: setup_guide.md
  - Dev Docs:
      - Agents: dev_docs/agents.md
      - LLM Clients: dev_docs/llm_clients.md
      - Data Models: dev_docs/data_models.md
      - Tools: dev_docs/tools.md
      - Logging: dev_docs/logging.md
      - File Management: dev_docs/file_manager.md
      - Secret Management: dev_docs/secrets.md
      - TradingGraph: dev_docs/trade.md
      - ChatGraph: dev_docs/chat.md
theme:
  name: material
  logo: images/logo.svg
  features:
    - content.code.copy

extra_css:
  - stylesheets/extra.css

plugins:
  - search
  - mkdocstrings

markdown_extensions:
  - pymdownx.highlight:
      use_pygments: true
  - pymdownx.superfences
