site_name: Syndicate
repo_url: https://github.com/mskmay66/syndicate
repo_name: mskmay66/syndicate
features:
  - navigation.indexes
nav:
  - Home: index.md
  - Usage: usage.md
  - Dev Docs:
      - Syndicate: reference/syndicate.md
theme:
  name: material
  features:
    - content.code.copy
  palette:
     # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: black
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
plugins:
  - search
  - mkdocstrings
